name: Build image -Push to docker hub -Deploy to EC2

# on: is event that triggers worflow execution
on:
  push:
    branches:
      - "main"

# jobs: is Set of steps. Can be 1 or more jobs in single Workflow
# build: is name of job
# runs-on: is runner/os on which workflow executes. It can be self-runner(your own pc) or VMs provided by github
# steps: is series of scripts
# needs: define job2 is dependent on job1
jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/CICD:latest

  deploy_job2:
    needs: build_job1
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # last script run image if exist locally otherwise pull image from dockerhub build container from it then run
          script: |
            sudo docker stop  amresh1808/clockbox || true
            sudo docker rm  amresh1808/clockbox || true
            sudo docker run -d --name amresh1808/clockbox -p 3000:3000 amresh1808/clockbox
